no.nav.security.jwt.client.registration:
  eux-rina-api:
    token-endpoint-url: dummy
  eux-nav-rinasak:
    token-endpoint-url: dummy
  pdl-web:
    token-endpoint-url: dummy
  pdl:
    token-endpoint-url: dummy
  oppgave-sak:
    token-endpoint-url: dummy
  saf:
    token-endpoint-url: dummy



